### ISSUE TITLE
Question - is it possible to use asynchronous functions with `Actor.of()` ? 

### ISSUE THREAD

**Issue by rehman-00001** [renatoathaydes/actors#11]
Let's say I have a function that returns a Future and `await`ing it returns the results.

```.dart
final results = await someHeavyAsyncFunction();
print(results);
```

It is possible to use this function with `Actor.of()`?
I tried using it. But it just doesn't return anything at all. Even when I place breakpoint on the print statement, it never hits there.

Just wanted to know if this library supports using asynchronous functions at all.

**Comment by renatoathaydes** [comment]
Are you sure you can use `const` there? Try `final` (`const` computations would run at compile time, probably not what you need?).

Any function should work since Dart 2.15 when they improved the Isolates API.

If it doesn't , please try to create a fully runnable example I can try myself.

I normally use it like this:

```dart
String message(String name) => 'hello $name';

main() async {
    final actor = Actor.of(message);
    final answer = await actor.send('Joe');
    print(answer);
    actor.close();
}
```

**Comment by renatoathaydes** [comment]
Full async example:

```dart
import 'package:actors/actors.dart';

Future<String> hello(String name) async =>
  'Hello $name';

main()async {
  final actor = Actor.of(hello);
  final answer = await  actor.send('Joe');
  print (answer);
  actor.close();
}
```

**Comment by rehman-00001** [comment]
My apologies. It is working fine. Sorry for the trouble.
