### ISSUE TITLE
Actor hangs when sent an unevaluated `Iterable`

### ISSUE THREAD

**Issue by btrautmann** [renatoathaydes/actors#16]
Hi there! First off, thanks so much for this package; it made pushing expensive operations onto background `Isolate`s really easy in my application, and the thought that went into providing the ability to use `LocalMessenger` around the same logic you use `Actor` for made testing/swapping `Isolate`s really easy.

I ran into an issue recently where an `Actor` was hanging, but using `LocalMessenger` worked just fine. I finally discovered that the issue was that I was sending an unevaluated (I believe that's the correct terminology...) `Iterable` to the `Actor`. This issue can be reproduced with the following snippet, which is also in [this repo](https://github.com/btrautmann/sync_star_repro) for ease of use.

```dart
void main(List<String> arguments) async {
  final map = {
    'a': [1, 2, 3],
    'b': [4, 5, 6],
    'c': [7, 8, 9],
  };
  // Call `toList()` to force evaluation of the iterable.
  final values = map.values.flattened;
  final actor = Actor<Iterable<int>, Iterable<int>>.of((message) {
    return message.map((e) => e * 2);
  });
  final result = await actor.send(values);
  await actor.close();
  print('Calculated: $result');
}
```
As the code is written above, any code after the `await actor.send(values)` invocation will never run. However, if you "evaluate" the `SyncStarIterable` returned by `flattened` using `toList()`, the logic works as expected.

I am unsure whether this is an issue with `actors` or a nuance of `Isolate`s that I'm not aware of. If the latter, I'm happy to port this issue over to `dart-lang` if we feel it's an actual issue and not just me being a dummy!

**Comment by renatoathaydes** [comment]
Hi @btrautmann . This is as expected because Dart `Iterable`s are by definition lazy. For it to work across Isolates, the receiver Isolate would need to be able to "invoke" the iterator's `next` method on the original Isolate, which is clearly impossible... for it to work, you need to "send" the whole collection, which is why calling `toList` fixes the problem.

Unfortunately , there's on way to "stream" messages to another actor, you must send them one by one, or all at once. But if you need to receive many items, it's possible by using `StreamActor` which only works on `Handler`s that return a `Stream`.
If you use that, you could send messages one by one while you await on items you get back via the `Stream`.

**Comment by renatoathaydes** [comment]
I should've checked first :(.

The example does work with pure Isolates:

```dart
import 'dart:isolate';

void go(Iterable<int> iter) {
  for (final i in iter) {
    print('Got item: $i');
  }
}

main() async {
final map = {
    'a': [1, 2, 3],
    'b': [4, 5, 6],
    'c': [7, 8, 9],
  };
  // Call `toList()` to force evaluation of the iterable.
  final values = map.values.expand((i) => i);
  final iso = await Isolate.spawn(go, values);
  await Future.delayed(Duration(seconds: 2));
  iso.kill();
}
```

I will investigate this when I get some time! I really didn't expect it.

**Comment by renatoathaydes** [comment]
To my surprise, it does work with Actors:

```dart
import 'package:actors/actors.dart';

class Printer with Handler<Iterable<int>, void> {
  @override
  void handle(Iterable<int> iter) {
    for (final i in iter) {
      print('Got item: $i');
    }
  }
}

main() async {
  final map = {
    'a': [1, 2, 3],
    'b': [4, 5, 6],
    'c': [7, 8, 9],
  };
  // Call `toList()` to force evaluation of the iterable.
  final values = map.values.expand((i) => i);
  final actor = Actor.create(Printer.new);
  await actor.send(values);
  await actor.close();
}
```

I tried all latest versions of actors and they all worked.

Could it be something else that's not working for you @btrautmann ? Where did you get `flattened` from? Maybe try as I did above and use `expand((i) => i)` which is basically flattening the iterable for you.

**Comment by renatoathaydes** [comment]
By the way, tested with Dart version:
```
Dart SDK version: 3.1.1 (stable) (Tue Sep 5 12:20:14 2023 +0000) on "macos_x64"
```
If you're using an older version, I guess that answers the question why it won't work for you.

**Comment by btrautmann** [comment]
Let me take a peek! Did you try reproducing in that repo I linked? `flattened` is from `package:collection` by the way.

**Comment by btrautmann** [comment]
@renatoathaydes I checked again with the linked repo and I'm seeing the same behavior 🤔 I'm using dart `3.2.3` by the way, bundled with the Flutter SDK (using `fvm`) version `3.16.4` (near-latest stable).

**Comment by renatoathaydes** [comment]
Your example works if you replace `flattened` with `expand((i) => i)` as I had suggested.
The problem seems related to the kind of `Iterable` returned by `flattened`. In general, it seems a bit dangerous anyway to try to use lazy values when sending messages between Isolates, as I was talking about in my first response here.
I don't think it should even work with `expand`. Message passing is always about immutable messages, data values, being exchanged between actors that cannot access each other's environments.

I will close this ticket because I don't see anything I can do about this anyway - and it's basically misusage of the actors model.

**Comment by btrautmann** [comment]
Just got bit by this again 🙃 

I am thinking it's related to https://github.com/dart-lang/sdk/issues/51757.

IIRC, when I dug down into the `actors` package the error here was being swallowed which is what made it so hard to debug. It would be amazing if that could be solved @renatoathaydes! Sadly, it's been too long since I was in the code to recall where that error is swallowed, but maybe you can find it quicker.

For now, I'll probably make a `safeFlatten` function that does the `expand` as to avoid making a lazy iterable (but with a function name that makes more sense to me).
